version: "3"
services:
  db:
    image: mongo:4.0.4
    container_name: db
    ports: 
      - 27017:27017
    volumes:
      - /home/docker/mongo-docker
    networks: 
      - mynet
  api:
    build: ./grupo3-backend
    container_name: api
    volumes:
      - /home/docker/api-docker
    ports:
      - 8080:8080
    depends_on:
      - db
    networks: 
      - mynet
    environment: 
      - MONGO_DB_URI=mongodb://db:27017
  telegram:
    build: ./grupo3-telegram-bot
    container_name: telegram
    depends_on:
      - api
    networks: 
      - mynet
    environment:
      - API_BASE_URI=http://api:8080
networks: 
  mynet:
